# -*- coding: utf-8 -*-
"""Assignment1_Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OBxlz1iVYlClB5qnADzX-SgGvMq-DI99
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly as p1
import plotly.express as px
import plotly.graph_objects as go1
# %matplotlib inline

url = 'https://drive.google.com/file/d/1Ar9eQUbgazhaDqDPbNDeqdBwJZiOUL11/view?usp=drivesdk'

data_frame = pd.read_csv("https://drive.google.com/uc?export=download&id="+url.split('/')[-2])
data_frame.head()
data_frame_copy = data_frame
print(data_frame)
data_frame.head()

data_frame.dtypes

data_frame.drop(columns=['Country Code','Indicator Name','Indicator Code'])



data_frame.fillna(0,inplace=True)
data_frame.head(10)

#data_frame.iloc[:,4:]=data_frame.iloc[:,4:].astype('int64').round(3)
Years = list(data_frame.columns)[1:]


def formatTo(x):
  if(not str(x).isdigit()):
    x =x.replace('$','')
    x = x.replace(',','')
  return float(x)

for i in Years:
  data_frame[i]=data_frame[i].apply(lambda x : "{:.1f}".format(formatTo(x)/1000))
data_frame

data_frametop5 = data_frame[data_frame['Country Name'].isin(['China','France','Russian Federation','United Kingdom','United States'])]
#fig = px.pie(data_frame,values='1960',names='Country Name',labels=Years)
#fig.show()
data_frametop5.sort_values(by="1960",ascending=True,inplace=True)
data_frametop5.head()
#fig = px.bar(data_frametop5,x='Country Name',y='1960',color='Country Name',title='Top 5 UNO countries GDP in 1960',barmode = 'stack')
#fig.show()


y1=data_frametop5['1960']
y2=data_frametop5['2021']
x=np.arange(len(data_frametop5['Country Name']))


def barPlot(names,y1,y2):
    '''
    The Top 5 Countries in United Nations Organization GDP Comparision which are China,France,United Kingdom,United Nations,Russian Federation
    Russian Federation GDP is 0 as it is formed in 1991
    The Graph 
    '''
    plt.figure(figsize=(10,6))
    width=0.4
    plt.bar(x-0.2,y1,width,color='b',label='1960')
    plt.bar(x+0.2,y2,width,color='g',label='2021')
    plt.xticks(x,data_frametop5['Country Name'])
    plt.xlabel("Country")
    plt.ylabel("GDP in $")
    plt.title("Top 5 UNO countries GDP in 1960 and 2021")
    plt.legend()
    plt.show()

print(barPlot.__doc__)
barPlot(x,y1,y2)

data_frametop10 = data_frame[data_frame['Country Name'].isin(['India','Germany','Spain','Japan','Brazil','Argentina','Belgium','Australia','Singapore','Qatar'])]
data_frametop10.sort_values(by='2021',ascending=False,inplace=True)

def linePlot():
  '''
  The top 10 most famous countries excluding best 5 UNO countries GDP comparision shows that, India is having a low GDP Compared to other countries where as Qatar and Singapore made their way for highest GDP

  '''
  years = ['2017','2018','2019','2020','2021']
  year1 = data_frametop10[data_frametop10['Country Name']=='India']
  year2 = data_frametop10[data_frametop10['Country Name']=='Germany']
  year3 = data_frametop10[data_frametop10['Country Name']=='Spain']
  year4 = data_frametop10[data_frametop10['Country Name']=='Japan']
  year5 = data_frametop10[data_frametop10['Country Name']=='Brazil']
  year6 = data_frametop10[data_frametop10['Country Name']=='Argentina']
  year7 = data_frametop10[data_frametop10['Country Name']=='Belgium']
  year8 = data_frametop10[data_frametop10['Country Name']=='Australia']
  year9 = data_frametop10[data_frametop10['Country Name']=='Singapore']
  year10 = data_frametop10[data_frametop10['Country Name']=='Qatar']
  x=np.arange(len(years))
  plt.figure(figsize=(12,14))
  plt.plot(x,np.array(year1[['2017','2018','2019','2020','2021']]).ravel(),color='r',label='India')
  plt.plot(x,np.array(year2[['2017','2018','2019','2020','2021']]).ravel(),color='b',label='Germany')
  plt.plot(x,np.array(year3[['2017','2018','2019','2020','2021']]).ravel(),color='g',label='Spain')
  plt.plot(x,np.array(year4[['2017','2018','2019','2020','2021']]).ravel(),color='orange',label='Japan')
  plt.plot(x,np.array(year5[['2017','2018','2019','2020','2021']]).ravel(),color='y',label='Brazil')
  plt.plot(x,np.array(year6[['2017','2018','2019','2020','2021']]).ravel(),color='pink',label='Argentina')
  plt.plot(x,np.array(year7[['2017','2018','2019','2020','2021']]).ravel(),color='violet',label='Belgium')
  plt.plot(x,np.array(year8[['2017','2018','2019','2020','2021']]).ravel(),color='grey',label='Australia')
  plt.plot(x,np.array(year9[['2017','2018','2019','2020','2021']]).ravel(),color='indigo',label='Singapore')
  plt.plot(x,np.array(year10[['2017','2018','2019','2020','2021']]).ravel(),color='m',label='Qatar')
  plt.xticks(x,years)
  plt.xlabel("Years")
  plt.ylabel("GDP in $")
  plt.title("The top 10 most famous  countries GDP from 2017 to 2021")
  plt.legend()
  plt.show()
  np.array(year1[['2017','2018','2019','2020','2021']]).ravel()


print(linePlot.__doc__)
linePlot()

data_frameanother5 = data_frame_copy.sort_values(by='2021',ascending=False)
data_frameanother5  = data_frameanother5[~data_frameanother5['Country Name'].isin(['China','France','Russian Federation','United Kingdom','United States'])]
#data_frameanother5=data_frameanother5.head(10)
data_frameanother5.fillna(0,inplace=True)

data_frameanother5 = data_frameanother5.head(20).tail(5)
countries = list(data_frameanother5['Country Name'])

def pieplot():
    '''
    GDP Comparision excluding top 5 UNO countries in 2020 and 2021
    The variation of each countries or Unions is depicted in two pie charts,Latin America and Carribean Countries have faced a slight rise in their GDP
    Early demographic dividend  consists Asia countries have seen a 8% increase in their GDP
    Euro Union has faced a 5% decrease in their GDP compared to 2020
    '''
    year = data_frameanother5['2020'].astype('float')
    plt.pie(year,labels=countries,autopct='%.1fK$')
    plt.title("2020 GDP of Countries which are not from top 5 UNO")
    plt.show()


    year = data_frameanother5['2021'].astype('float')
    plt.pie(year,labels=countries,autopct='%.1fK$')
    plt.title("2021 GDP of Countries which are not from top 5 UNO")
    plt.show()


print(pieplot.__doc__)
pieplot()



